import { PublicLayout, PageHero, PageBody, Section } from "@/components/public/PublicLayout";

export default function MedicalDisclaimer() {
  return (
    <PublicLayout
      seo={{
        title: "Medical Disclaimer",
        description: "Predict Disease by symptom.ai provides clinical decision support and does not diagnose Type 2 diabetes or replace professional medical judgment.",
        path: "/medical-disclaimer",
      }}
    >
      <PageHero title="Medical Disclaimer" />
      <PageBody>
        <Section>
          <p>
            Predict Disease is a clinical decision-support prototype intended to assist qualified
            healthcare professionals in reviewing information relevant to diabetes screening and
            care.
          </p>
          <p>
            Predict Disease does not independently establish a medical diagnosis, prescribe
            treatment, or replace professional medical judgment.
          </p>
          <p>
            Information generated by the platform may be incomplete or incorrect and must be
            interpreted in the context of the patient's complete clinical circumstances.
          </p>
          <p>The platform is not intended for emergency medical use.</p>
          <p>
            Patient-facing materials should not be used as a substitute for evaluation or advice from
            a qualified healthcare professional.
          </p>
        </Section>
      </PageBody>
    </PublicLayout>
  );
}
