// AUTO-GENERATED by @lovable.dev/mcp-js — do not edit. Regenerated by the Vite plugin.
// To take ownership, delete this banner line; the plugin then leaves the file alone.
// supabase function: mcp
// Bundled from src/lib/mcp/index.ts by @lovable.dev/mcp-js.
// src/lib/mcp/index.ts
import { auth, defineMcp } from "npm:@lovable.dev/mcp-js@0.22.2";

// src/lib/mcp/tools/add-patient-note.ts
import { createClient } from "npm:@supabase/supabase-js@^2.58.0";
import { defineTool } from "npm:@lovable.dev/mcp-js@0.22.2";
import { z } from "npm:zod@^3.25.76";
function supabaseForUser(ctx) {
  return createClient(process.env.SUPABASE_URL, process.env.SUPABASE_PUBLISHABLE_KEY, {
    global: { headers: { Authorization: `Bearer ${ctx.getToken()}` } },
    auth: { persistSession: false, autoRefreshToken: false }
  });
}
var add_patient_note_default = defineTool({
  name: "add_patient_note",
  title: "Add patient note",
  description: "Add a between-visit patient note for the signed-in user. The note is stored with a timestamp and queued for AI symptom analysis.",
  inputSchema: {
    note_text: z.string().trim().min(1).describe("Free-text note describing symptoms, feelings, or observations."),
    source: z.enum(["mcp", "manual", "email"]).optional().describe("Where the note came from (default 'mcp').")
  },
  annotations: { readOnlyHint: false, destructiveHint: false, openWorldHint: false },
  handler: async ({ note_text, source }, ctx) => {
    if (!ctx.isAuthenticated()) {
      return { content: [{ type: "text", text: "Not authenticated" }], isError: true };
    }
    const supabase = supabaseForUser(ctx);
    const patient_id = ctx.getUserId();
    const { data, error } = await supabase.from("patient_notes").insert({
      patient_id,
      note_text,
      source: source ?? "mcp",
      analysis_status: "pending"
    }).select().single();
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    return {
      content: [{ type: "text", text: `Note saved (id: ${data.id})` }],
      structuredContent: { note: data }
    };
  }
});

// src/lib/mcp/tools/list-patient-notes.ts
import { createClient as createClient2 } from "npm:@supabase/supabase-js@^2.58.0";
import { defineTool as defineTool2 } from "npm:@lovable.dev/mcp-js@0.22.2";
import { z as z2 } from "npm:zod@^3.25.76";
function supabaseForUser2(ctx) {
  return createClient2(process.env.SUPABASE_URL, process.env.SUPABASE_PUBLISHABLE_KEY, {
    global: { headers: { Authorization: `Bearer ${ctx.getToken()}` } },
    auth: { persistSession: false, autoRefreshToken: false }
  });
}
var list_patient_notes_default = defineTool2({
  name: "list_patient_notes",
  title: "List patient notes",
  description: "List the signed-in user's patient notes, newest first.",
  inputSchema: {
    limit: z2.number().int().min(1).max(50).optional().describe("Max number of notes to return (default 10).")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ limit }, ctx) => {
    if (!ctx.isAuthenticated()) {
      return { content: [{ type: "text", text: "Not authenticated" }], isError: true };
    }
    const { data, error } = await supabaseForUser2(ctx).from("patient_notes").select("id, note_text, ai_summary, analysis_status, created_at").order("created_at", { ascending: false }).limit(limit ?? 10);
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    return {
      content: [{ type: "text", text: JSON.stringify(data) }],
      structuredContent: { notes: data }
    };
  }
});

// src/lib/mcp/tools/list-patient-symptoms.ts
import { createClient as createClient3 } from "npm:@supabase/supabase-js@^2.58.0";
import { defineTool as defineTool3 } from "npm:@lovable.dev/mcp-js@0.22.2";
import { z as z3 } from "npm:zod@^3.25.76";
function supabaseForUser3(ctx) {
  return createClient3(process.env.SUPABASE_URL, process.env.SUPABASE_PUBLISHABLE_KEY, {
    global: { headers: { Authorization: `Bearer ${ctx.getToken()}` } },
    auth: { persistSession: false, autoRefreshToken: false }
  });
}
var list_patient_symptoms_default = defineTool3({
  name: "list_patient_symptoms",
  title: "List tracked symptoms",
  description: "List symptoms tracked for the signed-in user, most recent first.",
  inputSchema: {
    limit: z3.number().int().min(1).max(100).optional().describe("Max number of symptom rows (default 25).")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ limit }, ctx) => {
    if (!ctx.isAuthenticated()) {
      return { content: [{ type: "text", text: "Not authenticated" }], isError: true };
    }
    const { data, error } = await supabaseForUser3(ctx).from("patient_symptoms").select("id, symptom_name, severity, frequency, source, created_at").order("created_at", { ascending: false }).limit(limit ?? 25);
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    return {
      content: [{ type: "text", text: JSON.stringify(data) }],
      structuredContent: { symptoms: data }
    };
  }
});

// src/lib/mcp/tools/get-latest-insights.ts
import { createClient as createClient4 } from "npm:@supabase/supabase-js@^2.58.0";
import { defineTool as defineTool4 } from "npm:@lovable.dev/mcp-js@0.22.2";
function supabaseForUser4(ctx) {
  return createClient4(process.env.SUPABASE_URL, process.env.SUPABASE_PUBLISHABLE_KEY, {
    global: { headers: { Authorization: `Bearer ${ctx.getToken()}` } },
    auth: { persistSession: false, autoRefreshToken: false }
  });
}
var get_latest_insights_default = defineTool4({
  name: "get_latest_insights",
  title: "Get latest risk insights",
  description: "Return the most recent AI-generated similarity/risk insight for the signed-in user, including matching factors and recommendations.",
  inputSchema: {},
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async (_input, ctx) => {
    if (!ctx.isAuthenticated()) {
      return { content: [{ type: "text", text: "Not authenticated" }], isError: true };
    }
    const { data, error } = await supabaseForUser4(ctx).from("patient_similarity_analysis").select("*").order("created_at", { ascending: false }).limit(1).maybeSingle();
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    if (!data) {
      return { content: [{ type: "text", text: "No insights generated yet." }] };
    }
    return {
      content: [{ type: "text", text: JSON.stringify(data) }],
      structuredContent: { insights: data }
    };
  }
});

// src/lib/mcp/tools/get-risk-score.ts
import { createClient as createClient5 } from "npm:@supabase/supabase-js@^2.58.0";
import { defineTool as defineTool5 } from "npm:@lovable.dev/mcp-js@0.22.2";
function sb(ctx) {
  return createClient5(process.env.SUPABASE_URL, process.env.SUPABASE_PUBLISHABLE_KEY, {
    global: { headers: { Authorization: `Bearer ${ctx.getToken()}` } },
    auth: { persistSession: false, autoRefreshToken: false }
  });
}
var get_risk_score_default = defineTool5({
  name: "get_risk_score",
  title: "Get latest diabetes risk score",
  description: "Return the most recent computed diabetes risk score (0-100), probability, and per-feature contributions for the signed-in user.",
  inputSchema: {},
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async (_i, ctx) => {
    if (!ctx.isAuthenticated()) return { content: [{ type: "text", text: "Not authenticated" }], isError: true };
    const { data, error } = await sb(ctx).from("patient_risk_scores").select("*").order("computed_at", { ascending: false }).limit(1).maybeSingle();
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    if (!data) return { content: [{ type: "text", text: "No risk score computed yet. Call recompute_risk_score first." }] };
    return { content: [{ type: "text", text: JSON.stringify(data) }], structuredContent: { risk: data } };
  }
});

// src/lib/mcp/tools/recompute-risk-score.ts
import { defineTool as defineTool6 } from "npm:@lovable.dev/mcp-js@0.22.2";
var recompute_risk_score_default = defineTool6({
  name: "recompute_risk_score",
  title: "Recompute diabetes risk score",
  description: "Recompute the diabetes risk score for the signed-in user from their current symptoms, profile, and notes.",
  inputSchema: {},
  annotations: { readOnlyHint: false, idempotentHint: true, openWorldHint: false },
  handler: async (_i, ctx) => {
    if (!ctx.isAuthenticated()) return { content: [{ type: "text", text: "Not authenticated" }], isError: true };
    const res = await fetch(`${process.env.SUPABASE_URL}/functions/v1/compute-risk-score`, {
      method: "POST",
      headers: {
        "Content-Type": "application/json",
        Authorization: `Bearer ${ctx.getToken()}`
      },
      body: JSON.stringify({ patientId: ctx.getUserId() })
    });
    const body = await res.json();
    if (!res.ok) return { content: [{ type: "text", text: body.error ?? "Compute failed" }], isError: true };
    return { content: [{ type: "text", text: JSON.stringify(body.risk) }], structuredContent: { risk: body.risk } };
  }
});

// src/lib/mcp/tools/get-similar-patients.ts
import { createClient as createClient6 } from "npm:@supabase/supabase-js@^2.58.0";
import { defineTool as defineTool7 } from "npm:@lovable.dev/mcp-js@0.22.2";
function sb2(ctx) {
  return createClient6(process.env.SUPABASE_URL, process.env.SUPABASE_PUBLISHABLE_KEY, {
    global: { headers: { Authorization: `Bearer ${ctx.getToken()}` } },
    auth: { persistSession: false, autoRefreshToken: false }
  });
}
var get_similar_patients_default = defineTool7({
  name: "get_similar_patients",
  title: "Get similar-patient cohort",
  description: "Return the cohort the signed-in user has been clustered into, its centroid features, size, average risk, and top interventions that worked for similar patients.",
  inputSchema: {},
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async (_i, ctx) => {
    if (!ctx.isAuthenticated()) return { content: [{ type: "text", text: "Not authenticated" }], isError: true };
    const client = sb2(ctx);
    const { data: assign } = await client.from("patient_cohort_assignments").select("*").order("computed_at", { ascending: false }).limit(1).maybeSingle();
    if (!assign) return { content: [{ type: "text", text: "No cohort assignment yet. Ask an admin to run compute-cohorts." }] };
    const { data: cohort } = await client.from("cohorts").select("*").eq("id", assign.cohort_id).maybeSingle();
    const payload = { assignment: assign, cohort };
    return { content: [{ type: "text", text: JSON.stringify(payload) }], structuredContent: payload };
  }
});

// src/lib/mcp/tools/get-symptom-forecast.ts
import { createClient as createClient7 } from "npm:@supabase/supabase-js@^2.58.0";
import { defineTool as defineTool8 } from "npm:@lovable.dev/mcp-js@0.22.2";
import { z as z4 } from "npm:zod@^3.25.76";
function sb3(ctx) {
  return createClient7(process.env.SUPABASE_URL, process.env.SUPABASE_PUBLISHABLE_KEY, {
    global: { headers: { Authorization: `Bearer ${ctx.getToken()}` } },
    auth: { persistSession: false, autoRefreshToken: false }
  });
}
var get_symptom_forecast_default = defineTool8({
  name: "get_symptom_forecast",
  title: "Get symptom forecast",
  description: "Return per-symptom weekly history, a 4-week forecast, trend label (improving/stable/worsening), and anomaly flag for the signed-in user.",
  inputSchema: {
    symptom_name: z4.string().optional().describe("Filter to a specific symptom."),
    limit: z4.number().int().min(1).max(50).optional().describe("Max rows (default 10).")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ symptom_name, limit }, ctx) => {
    if (!ctx.isAuthenticated()) return { content: [{ type: "text", text: "Not authenticated" }], isError: true };
    let q = sb3(ctx).from("symptom_forecasts").select("*").order("computed_at", { ascending: false }).limit(limit ?? 10);
    if (symptom_name) q = q.eq("symptom_name", symptom_name);
    const { data, error } = await q;
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    return { content: [{ type: "text", text: JSON.stringify(data) }], structuredContent: { forecasts: data } };
  }
});

// src/lib/mcp/tools/get-population-metrics.ts
import { createClient as createClient8 } from "npm:@supabase/supabase-js@^2.58.0";
import { defineTool as defineTool9 } from "npm:@lovable.dev/mcp-js@0.22.2";
import { z as z5 } from "npm:zod@^3.25.76";
function sb4(ctx) {
  return createClient8(process.env.SUPABASE_URL, process.env.SUPABASE_PUBLISHABLE_KEY, {
    global: { headers: { Authorization: `Bearer ${ctx.getToken()}` } },
    auth: { persistSession: false, autoRefreshToken: false }
  });
}
var KEYS = ["risk_histogram", "symptom_prevalence", "age_vs_risk", "cohort_summary", "totals"];
var get_population_metrics_default = defineTool9({
  name: "get_population_metrics",
  title: "Get population analytics snapshot",
  description: "Return the latest aggregate population metrics: risk histogram, symptom prevalence, age vs risk, cohort summary, or totals.",
  inputSchema: {
    metric: z5.enum(KEYS).optional().describe("Which metric to return; omit for all.")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ metric }, ctx) => {
    if (!ctx.isAuthenticated()) return { content: [{ type: "text", text: "Not authenticated" }], isError: true };
    let q = sb4(ctx).from("population_metrics").select("*").order("snapshot_date", { ascending: false }).limit(20);
    if (metric) q = q.eq("metric_key", metric);
    const { data, error } = await q;
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    const latest = /* @__PURE__ */ new Map();
    for (const r of data ?? []) if (!latest.has(r.metric_key)) latest.set(r.metric_key, r);
    const out = Array.from(latest.values());
    return { content: [{ type: "text", text: JSON.stringify(out) }], structuredContent: { metrics: out } };
  }
});

// src/lib/mcp/index.ts
var projectRef = "hcwvalwioskpzttqefwu";
var mcp_default = defineMcp({
  name: "predict-disease-mcp",
  title: "Predict Disease MCP",
  version: "0.2.0",
  instructions: "Tools for the Predict Disease app. Patients can log notes/symptoms, retrieve their AI risk insights, get a computed diabetes risk score with feature contributions, find similar-patient cohorts, view symptom forecasts, and read aggregate population metrics. All tools act as the signed-in user.",
  auth: auth.oauth.issuer({
    issuer: `https://${projectRef}.supabase.co/auth/v1`,
    acceptedAudiences: "authenticated"
  }),
  tools: [
    add_patient_note_default,
    list_patient_notes_default,
    list_patient_symptoms_default,
    get_latest_insights_default,
    get_risk_score_default,
    recompute_risk_score_default,
    get_similar_patients_default,
    get_symptom_forecast_default,
    get_population_metrics_default
  ]
});

// lovable-mcp-supabase-entry.ts
import { createSupabaseHandler } from "npm:@lovable.dev/mcp-js@0.22.2/stacks/supabase";
Deno.serve(createSupabaseHandler(mcp_default, { functionName: "mcp" }));
