// AUTO-GENERATED by @lovable.dev/mcp-js — do not edit. Regenerated by the Vite plugin.
// To take ownership, delete this banner line; the plugin then leaves the file alone.
// supabase function: mcp
// Bundled from src/lib/mcp/index.ts by @lovable.dev/mcp-js.
// src/lib/mcp/index.ts
import { auth, defineMcp } from "npm:@lovable.dev/mcp-js@0.22.2";

// src/lib/mcp/tools/add-patient-note.ts
import { createClient } from "npm:@supabase/supabase-js@^2.58.0";
import { defineTool } from "npm:@lovable.dev/mcp-js@0.22.2";
import { z } from "npm:zod@^3.25.76";
function supabaseForUser(ctx) {
  return createClient(process.env.SUPABASE_URL, process.env.SUPABASE_PUBLISHABLE_KEY, {
    global: { headers: { Authorization: `Bearer ${ctx.getToken()}` } },
    auth: { persistSession: false, autoRefreshToken: false }
  });
}
var add_patient_note_default = defineTool({
  name: "add_patient_note",
  title: "Add patient note",
  description: "Add a between-visit patient note for the signed-in user. The note is stored with a timestamp and queued for AI symptom analysis.",
  inputSchema: {
    note_text: z.string().trim().min(1).describe("Free-text note describing symptoms, feelings, or observations."),
    source: z.enum(["mcp", "manual", "email"]).optional().describe("Where the note came from (default 'mcp').")
  },
  annotations: { readOnlyHint: false, destructiveHint: false, openWorldHint: false },
  handler: async ({ note_text, source }, ctx) => {
    if (!ctx.isAuthenticated()) {
      return { content: [{ type: "text", text: "Not authenticated" }], isError: true };
    }
    const supabase = supabaseForUser(ctx);
    const patient_id = ctx.getUserId();
    const { data, error } = await supabase.from("patient_notes").insert({
      patient_id,
      note_text,
      source: source ?? "mcp",
      analysis_status: "pending"
    }).select().single();
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    return {
      content: [{ type: "text", text: `Note saved (id: ${data.id})` }],
      structuredContent: { note: data }
    };
  }
});

// src/lib/mcp/tools/list-patient-notes.ts
import { createClient as createClient2 } from "npm:@supabase/supabase-js@^2.58.0";
import { defineTool as defineTool2 } from "npm:@lovable.dev/mcp-js@0.22.2";
import { z as z2 } from "npm:zod@^3.25.76";
function supabaseForUser2(ctx) {
  return createClient2(process.env.SUPABASE_URL, process.env.SUPABASE_PUBLISHABLE_KEY, {
    global: { headers: { Authorization: `Bearer ${ctx.getToken()}` } },
    auth: { persistSession: false, autoRefreshToken: false }
  });
}
var list_patient_notes_default = defineTool2({
  name: "list_patient_notes",
  title: "List patient notes",
  description: "List the signed-in user's patient notes, newest first.",
  inputSchema: {
    limit: z2.number().int().min(1).max(50).optional().describe("Max number of notes to return (default 10).")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ limit }, ctx) => {
    if (!ctx.isAuthenticated()) {
      return { content: [{ type: "text", text: "Not authenticated" }], isError: true };
    }
    const { data, error } = await supabaseForUser2(ctx).from("patient_notes").select("id, note_text, ai_summary, analysis_status, created_at").order("created_at", { ascending: false }).limit(limit ?? 10);
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    return {
      content: [{ type: "text", text: JSON.stringify(data) }],
      structuredContent: { notes: data }
    };
  }
});

// src/lib/mcp/tools/list-patient-symptoms.ts
import { createClient as createClient3 } from "npm:@supabase/supabase-js@^2.58.0";
import { defineTool as defineTool3 } from "npm:@lovable.dev/mcp-js@0.22.2";
import { z as z3 } from "npm:zod@^3.25.76";
function supabaseForUser3(ctx) {
  return createClient3(process.env.SUPABASE_URL, process.env.SUPABASE_PUBLISHABLE_KEY, {
    global: { headers: { Authorization: `Bearer ${ctx.getToken()}` } },
    auth: { persistSession: false, autoRefreshToken: false }
  });
}
var list_patient_symptoms_default = defineTool3({
  name: "list_patient_symptoms",
  title: "List tracked symptoms",
  description: "List symptoms tracked for the signed-in user, most recent first.",
  inputSchema: {
    limit: z3.number().int().min(1).max(100).optional().describe("Max number of symptom rows (default 25).")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ limit }, ctx) => {
    if (!ctx.isAuthenticated()) {
      return { content: [{ type: "text", text: "Not authenticated" }], isError: true };
    }
    const { data, error } = await supabaseForUser3(ctx).from("patient_symptoms").select("id, symptom_name, severity, frequency, source, created_at").order("created_at", { ascending: false }).limit(limit ?? 25);
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    return {
      content: [{ type: "text", text: JSON.stringify(data) }],
      structuredContent: { symptoms: data }
    };
  }
});

// src/lib/mcp/tools/get-latest-insights.ts
import { createClient as createClient4 } from "npm:@supabase/supabase-js@^2.58.0";
import { defineTool as defineTool4 } from "npm:@lovable.dev/mcp-js@0.22.2";
function supabaseForUser4(ctx) {
  return createClient4(process.env.SUPABASE_URL, process.env.SUPABASE_PUBLISHABLE_KEY, {
    global: { headers: { Authorization: `Bearer ${ctx.getToken()}` } },
    auth: { persistSession: false, autoRefreshToken: false }
  });
}
var get_latest_insights_default = defineTool4({
  name: "get_latest_insights",
  title: "Get latest risk insights",
  description: "Return the most recent AI-generated similarity/risk insight for the signed-in user, including matching factors and recommendations.",
  inputSchema: {},
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async (_input, ctx) => {
    if (!ctx.isAuthenticated()) {
      return { content: [{ type: "text", text: "Not authenticated" }], isError: true };
    }
    const { data, error } = await supabaseForUser4(ctx).from("patient_similarity_analysis").select("*").order("created_at", { ascending: false }).limit(1).maybeSingle();
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    if (!data) {
      return { content: [{ type: "text", text: "No insights generated yet." }] };
    }
    return {
      content: [{ type: "text", text: JSON.stringify(data) }],
      structuredContent: { insights: data }
    };
  }
});

// src/lib/mcp/index.ts
var projectRef = "hcwvalwioskpzttqefwu";
var mcp_default = defineMcp({
  name: "predict-disease-mcp",
  title: "Predict Disease MCP",
  version: "0.1.0",
  instructions: "Tools for the Predict Disease app. Patients can add between-visit notes, list their tracked symptoms and notes, and read the latest AI risk insight. All tools act as the signed-in user.",
  auth: auth.oauth.issuer({
    issuer: `https://${projectRef}.supabase.co/auth/v1`,
    acceptedAudiences: "authenticated"
  }),
  tools: [add_patient_note_default, list_patient_notes_default, list_patient_symptoms_default, get_latest_insights_default]
});

// lovable-mcp-supabase-entry.ts
import { createSupabaseHandler } from "npm:@lovable.dev/mcp-js@0.22.2/stacks/supabase";
Deno.serve(createSupabaseHandler(mcp_default, { functionName: "mcp" }));
